version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: natnael0024/piper:latest
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - 3307:3307
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: yourpassword
      MYSQL_ROOT_PASSWORD: yourrootpassword
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: yourrootpassword
volumes:
  db_data: